### ISSUE TITLE
Validation of SSL cert

### ISSUE THREAD

**Issue by unsystemizer** [IndieSquare/counterwallet#1]
https://github.com/IndieSquare/counterwallet/blob/master/app/lib/require/network.js#L17 - should this be "TRUE"?

**Comment by YutaHoshino** [comment]
Sorry my late reply.
You are right. It was way to avoid some errors on our development environment.
(Even in this case, it will keep HTTPClient run over HTTPS.)

We resolved it. In the next update, it will always be true.
Thanks.

**Comment by YutaHoshino** [comment]
Updated.
