### ISSUE TITLE
Fail to launch App

### ISSUE THREAD

**Issue by Ankarrr** [IndieSquare/counterwallet#11]
![screenshot_20160504-110852](https://cloud.githubusercontent.com/assets/8311552/15004368/c6bcc9ee-11e8-11e6-94f0-23b8820791e4.png)

After click "確定“:
![screenshot_20160504-110900](https://cloud.githubusercontent.com/assets/8311552/15004377/e61ff98c-11e8-11e6-868f-87a61721535f.png)

After click "確定" again, nothing happen

**Comment by Ankarrr** [comment]
Android 6.0.1, Nexus 5X

**Comment by YutaHoshino** [comment]
Thank you for pointing out.
I fixed this bug on ver0.9.5.
