### ISSUE TITLE
Better error handling for failed connection

### ISSUE THREAD

**Issue by unsystemizer** [IndieSquare/counterwallet#3]
* iOS 9.x
* Current Wallet
* On startup, I get 
```
Alert
Error: HTTP error
[OK]
```
* After I press OK, the app doesn't exit or try to reconnect

Expected behavior:
* Modify error string (e.g. `Connection error, please press "Exit" to try later or press "Retry" to connect now`)
* Maybe query some 3rd party site to check if CP server is up (if no, "Server Down"). This could also be shown as Server Status (Red/Green or Up/Down) in connection dialog box.

**Comment by YutaHoshino** [comment]
Thank you for your help.

Now we are changing error messages to the word easily understandable.
And from ver0.8.0, Indiesquare wallet shows dedicated message when reorganization occurred.

server status color is good idea. I’d like to consider about it.
