### ISSUE TITLE
cannot send more than 999 tokens - Input Amount to Sendwith numbers

### ISSUE THREAD

**Issue by eshriek** [IndieSquare/counterwallet#5]
I used IndieSquare Wallet to buy SOG cards (2 XAJIYEREMAAR for 1000 BITCRYSTALS) on November 3 2015.

Since that time there may have been a update after which the "," symbol is seen as part of the number and therefore returns invalid. I was only able to send 600 BITCRYSTALS for 1 XAJIBESAAR. If I tried to send 1,200 BITCRYSTALS it fails with the message, "Input Amount to Sendwtih numbers."

**Comment by southsideGLA** [comment]
+1 that, we tried to send 10,000 Scotcoins, but the error stopped us from buying a pint at our local :-| Definitely caused by the number formatting.

**Comment by southsideGLA** [comment]
not sure, but i think it will be something like this causing it?
https://github.com/IndieSquare/counterwallet/blob/bac6bf6375ec8e026727a012bbd044f0af9d2a29/app/lib/window/shapeshift.js#L378

**Comment by YutaHoshino** [comment]
Sorry for your inconvenience...
I fixed this issue on ver0.8.1. Thank you for pointing out.

**Comment by bitsacer** [comment]
Hey, great app . Would you be interested in providing a similar wallet app for BitShares ? Stop by BitShares forum to learn about worker-proposals,  there is a nice self sustainable system that pays out well.  bitsharestalk.org or bitshares.org
