### ISSUE TITLE
Wrong tx fee rounding error

### ISSUE THREAD

**Issue by unsystemizer** [IndieSquare/counterwallet#6]
https://www.blocktrail.com/BTC/tx/094ac30b7a727f343ce76b7878726e49092c58af642eab802a2d427088bb9023

An extra 0.00000001 BTC was added to fx fee cost making the total amount paid too small.

**Comment by YutaHoshino** [comment]
Oh... it is our api side bug. I will fix it.

**Comment by YutaHoshino** [comment]
I implemented optimal fee for app ver0.9.5.
