### ISSUE TITLE
Wrong display language

### ISSUE THREAD

**Issue by ashelukha** [IndieSquare/counterwallet#7]
I'm using Ukrainian language on my phone. After installing app it displays Japanese symbols. I need ability to select language in phone settings. Or use English for locales that are different from  Japanese

**Comment by YutaHoshino** [comment]
Thank you for message. Fixed it. Please wait for the app update.
https://git.io/vwO8B

**Comment by m4rky77** [comment]
I try to use the app in appstore and i has the same problem. I'm using spanish language in my ipad.
