### ISSUE TITLE
Left over bitcoins because of incorrect fee.

### ISSUE THREAD

**Issue by Codes4Fun** [IndieSquare/counterwallet#8]
I was trying to empty my wallet of BTC and was presented with a weird fee of 0.0001543, it would not let me send the transaction (produced a strange error in a foreign language) until I lowered my transaction to include the specified fee, and when the transaction finished I see it ended up only using 0.0001 for the fee and now I have 0.0000543 left in my wallet.

I saw another issue that mentions rounding errors with fees, so maybe this is related.

**Comment by YutaHoshino** [comment]
Oh, sorry but wrong fee displayed…
It should be 0.0001btc. 0.0000543btc is for the counerparty token. I will fix it.
